### PR TITLE
Update to 40.0

### PR DESCRIPTION
**Pull request by sophie-h**

### CODE REVIEW

**Comment by sophie-h** [comment]
bot, build

**Comment by X-m7** [comment]
FYI 40.1 is out now.

**Comment by sophie-h** [comment]
@mlundblad is there anything more I can help with to keep Maps on Flathub up-to-date?

I have also been made aware of https://github.com/flathub/flatpak-external-data-checker that allows for automatic pull requests when dependencies get updated. I could add the required data to the manifest if you like.

**Comment by mlundblad** [comment]
> @mlundblad is there anything more I can help with to keep Maps on Flathub up-to-date?
> 
> I have also been made aware of https://github.com/flathub/flatpak-external-data-checker that allows for automatic pull requests when dependencies get updated. I could add the required data to the manifest if you like.

Thanks!
Sounds good!

**Comment by bilelmoussaoui** [comment]
I suppose its fine to merge this one now? :)

**Pull request closed without merging**
