### PR TITLE
Update the runtime to the latest stable GNOME runtime (3.30)

### PR DESCRIPTION
**Pull request by andreasn**
An attempt to fix https://github.com/flathub/flathub/issues/667
Unfortunately I was unable to update to the newest runtime (3.30) because I couldn't get that to build (due to libgee apparently)

@mlundblad let me know if you have any success with 3.30 as a runtime

### CODE REVIEW

**Comment by andreasn** [comment]
@nedrichards https://github.com/flathub/org.gnome.Maps/commit/a87fa61412e916ad16b65146ebc324a90cbe8d1d mentions that network access is broken on the 3.28 runtime, but it worked fine here as far as I can see. Let me know if this still happens for you.

**Comment by andreasn** [comment]
this is the build error I get when I try to use 3.30 as a runtime:
```
If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /usr/bin/mkdir -p '/usr/share/gir-1.0'
 /usr/bin/install -c -m 644 Gee-0.8.gir '/usr/share/gir-1.0'
/usr/bin/install: cannot create regular file '/usr/share/gir-1.0/Gee-0.8.gir': Read-only file system
make[2]: *** [Makefile:1267: install-dist_girDATA] Error 1
make[2]: Leaving directory '/run/build/libgee/gee'
make[1]: *** [Makefile:1446: install-am] Error 2
make[1]: Leaving directory '/run/build/libgee/gee'
make: *** [Makefile:503: install-recursive] Error 1
Error: module libgee: Child process exited with code 2


```

**Comment by andreasn** [comment]
If I copy this build snippet https://github.com/flathub/org.gnome.FeedReader/commit/0553ee3ae107c81aa7852e9f890dd117652f291f#diff-0da5992ed681c006c25544526468b58bR36 I get a little bit further, but then it fails on evolution-data-server

**Comment by andreasn** [comment]
Got further when I added this build option to evolution-data-server https://github.com/flathub/org.gnome.Calendar/blob/368b0e3caf69395092fc409cce00d0b90d4db7b7/org.gnome.Calendar.json#L128

But, now folks fails because I disabled introspection on libgee :)

**Comment by TingPing** [comment]
> But, now folks fails because I disabled introspection on libgee :)

Just pass `girdir=/app/...` and `typelibdir=/app/...` to `make-install-args`.

**Comment by andreasn** [comment]
I think I got it building now

**Comment by andreasn** [comment]
But it won't run (from GNOME Builder at least) due to Cairo as a unsatisfied dependency (?!), so happy if others can try it out before a merge.

**Comment by TingPing** [comment]
bot, build

**Comment by nedrichards** [comment]
I've tested locally but this still doesn't work on my system (always says that it's offline) I'm pretty sure this a regression issue in GNetworkMonitorPortal that we're tracking internally at Endless for one of our apps as well (and given that we're looking at it I hope this'll get fixed soon and this ticket will be unblocked).

**Comment by Exalm** [comment]
Interesting. Running the current commit with `--runtime=org.gnome.Platform//3.30` fixes the always offline issue here.

**Comment by nedrichards** [comment]
testbot, build

**Comment by nedrichards** [comment]
fixed by https://github.com/flathub/org.gnome.Maps/commit/fc55d4bd5fdb5418347708ae495870272b90b4eb thanks for your persistance and patience!

**Pull request closed without merging**
