### PR TITLE
Update Maps and GNOME Runtime to 3.38 

### PR DESCRIPTION
**Pull request by Eonfge**
@bilelmoussaoui Wait, no it isn't, my pull request is a 1000% times better then @A6GibKm because I also updated the evolution data server to 3.38.**1** :p

Really, we should work a bit on coordination

### CODE REVIEW

**Comment by Eonfge** [comment]
bot, build

**Comment by A6GibKm** [comment]
> evolution data server to 3.38.1 :p

Not fair, it was not released a week ago. Indeed this could be coordinated in a better way.

**Comment by Eonfge** [comment]
Or we turn it into a game, like a whack-a-mole where we race to get Bilal's approval first ;)

Not sure how to better coordinate this though. Perhaps we should have a place where all dependencies are more clearly visible. Right now, it's all over the place

**Comment by A6GibKm** [comment]
I personally have some gnome apps tag releases in my rss feed. Id guess that one could make a python script to automatically generate updates for GNOME apps and dependencies which use https://download.gnome.org/sources/.

**Comment by bilelmoussaoui** [comment]
I'm often on Matrix, we could setup a room channel and discuss the tasks we have each release. There are also plans to have a gnome checker to update the modules using download.gnome.org as source for their modules.

**Comment by Eonfge** [comment]
bot, build

Quick bot, we must stay ahead of @A6GibKm

**Pull request merged**
