### PR TITLE
Use shared-modules for libcanberra and clutter

### PR DESCRIPTION
**Pull request by A6GibKm**
Includes relevant patch that fixes libcanberra use in wayland.

### CODE REVIEW

**Comment by A6GibKm** [comment]
bot, build

**Comment by mlundblad** [comment]
There was a lot of stuff updated in shared-modules, but I guess this is to be expected?

**Comment by A6GibKm** [comment]
Yes, no way around that, it just bumps their commit.

**Comment by mlundblad** [comment]
> 

Ahh, ok!

**Comment by mlundblad** [comment]
Looks good!

**Comment by mlundblad** [comment]
Thanks!

**Pull request merged**
